config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items do
    member do
      post :mark
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :file_location, ItemImageUploader
  #validates_presence_of :title, :duedate, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, :only => [:show, :edit, :update, :destroy, :mark]

  def index
    @items = Item.all
  end

  def mark
    @item.update(mark: !(@item.mark))
  end

  def new
    @item = Item.new
  
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url
    else
      render  :action => :new
    end
  end

  def update

    if @item.update_attributes(item_params)
      redirect_to item_path(@item)
    else
      render  :action => :edit
    end
  end

  def destroy
    
    @item.destroy

    redirect_to items_url
  end
 
private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :duedate, :note, :description, :file_location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mark(item)
    if item.important == 1
        "!!!"
      else
        " "
      end
    end
    end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="form container">
<%= form_for @item do |f| %>

  <div class="form-group"> 
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :duedate, "Due Date" %>
    <%= f.text_field :duedate, class: "form-control" %>
    
  </div>
  
  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :note, "Note" %>
    <%= f.text_field :note, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :file_location, "File Location" %>
    <%= f.file_field :file_location %>
  </div>
  
   
    <%= f.submit  %>
    <%=link_to 'Back to index', items_path, class: 'btn btn-default'  %>


<% end %>
 
<% if @item.errors.present? %>
  <ul>
    <% @item.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

app/views/items/edit.html.erb
<%= render :partial => "form" %>

app/views/items/index.html.erb
<table class ="table table-striped table-condensed" >
  <div class="sticker"> HY's To-Do-List</div>
      
  <tr>
    <td>Done</td>
    <td>Title</td>
    <td>Due Date</td>
    <td>Note</td>
    <td>Content</td>
    <td>Update</td>
    <td>Delete</td>
  </tr>


<% @items.each do |item|%>
  <tr>
     <td><%= check_box_tag :mark, true , item.mark, data: { url: mark_item_path(item), method: :post, remote: true } %></td>
     <td><%= item.title %></td>
     <td><%= item.duedate %></td>
     <td><%= item.note %></td>
     <td><%= link_to 'Show', item_path(item) %></td>
     <td><%= link_to 'Edit', edit_item_path(item) %></td>
     <td><%= link_to 'X', item_path(item), method: :delete, data:{ confirm: "Are you sure?" } %></td>
     

  </tr>
<% end %>
</table>


<%= link_to 'Add New list', new_item_path, class: 'btn btn-default' %>
<%= link_to 'Delete', check_box_tag(:done, 1), method: :delete, data:{ confirm: "Are you sure?" } %>

app/views/items/new.html.erb
<%= render :partial => "form" %>

app/views/items/show.html.erb
<div class="show container" > 
  <div class="show_box"> 
    <p class="title">Title :<%= @item.title %> </p>
    <p class="duedate">Due Date : <%= @item.duedate %></p>
    <p class="description">Description :<%= simple_format(@item.description) %></p>
    <p class="note"> Note : <%= @item.note %></p>
    <%= image_tag @item.file_location.url, size: "250x250", class: "img-thumbnail"%>
  </div>

  <div class="show_btn", margin= 20*20> 
    <%=link_to 'Back to index', items_path, class: 'btn btn-default'  %>
    <%=link_to 'Edit', edit_item_path(@item), class: 'btn btn-default'  %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>